name: football_user_app
description: User app (read-only) for matches, teams & tournaments.
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  intl: ^0.19.0
  cached_network_image: ^3.2.4
  provider: ^6.1.2
  image_picker: ^1.1.2
  firebase_storage: ^12.4.10
  firebase_auth: ^5.6.2
  shared_preferences: ^2.2.2
  firebase_messaging:
  firebase_crashlytics: ^4.3.10
  firebase_analytics:
  rxdart: ^0.27.7
  cloud_functions: ^5.6.0



flutter:
  uses-material-design: true

